---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install the vscode editor on RHEL or Fedora based systems
  when: ansible_distribution == target_ansible_distribution and 'code' not in ansible_facts.packages
  block:

    - name: Copy Microsoft key to remote host
      ansible.builtin.copy:
        src: "{{ role_path }}/files/microsoft.asc"
        dest: "/tmp/microsoft.asc"
        owner: root
        group: root
        mode: 0400
      become: true

    - name: Verify the the Microsoft key, using a fingerprint, before import
      ansible.builtin.rpm_key:
        key: /tmp/microsoft.asc
        fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
        validate_certs: true
      become: true

    - name: Add official Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        enabled: true
        file: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        sslverify: true
      become: true

    - name: Update package cache
      ansible.builtin.dnf:
        name: "*"
        update_only: true
      become: true

    - name: Install code package
      ansible.builtin.dnf:
        name: code
        state: present
      become: true
