---
- name: Ping host and test ssh connection
  hosts: "{{ target_hostname }}"
  roles:
    - ping_host

- name: Prepare workstation
  hosts: "{{ target_hostname }}"
  roles:
    - set_hostname

- name: Install developer packages
  hosts: "{{ target_hostname }}"
  roles:
    - developer

- name: Install packages
  hosts: "{{ target_hostname }}"
  roles:
    - install_packages

- name: Configure virtualization
  hosts: "{{ target_hostname }}"
  roles:
    - virtualization

- name: Configure cockpit
  hosts: "{{ target_hostname }}"
  roles:
    - cockpit
