---
- name: Ping host and test ssh connection
  hosts: "{{ target_hostname }}"
  roles:
    - ping_host

- name: Prepare workstation
  hosts: "{{ target_hostname }}"
  roles:
    - set_hostname
    - generate_ssh_keys

- name: Install developer packages
  hosts: "{{ target_hostname }}"
  roles:
    - developer

- name: Install packages
  hosts: "{{ target_hostname }}"
  roles:
    - install_packages

- name: Configure Gnome desktop
  hosts: "{{ target_hostname }}"
  roles:
    - gnome_desktop
