---
- name: Force systemd to reread config, enable and start service cockpit.socket
  become: true
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted
    daemon_reload: true
    enabled: true
  when: _cockpit_install.changed
