---
- name: Install Internet packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ internet }}"
  become: true
  when: "internet_packages"

- name: Set up multimedia
  ansible.builtin.include_tasks:
    multimedia.yaml
  when: "multimedia"

- name: Install utilities
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ utilities }}"
  become: true
  when: "utilities"
