---

internet:
  - chromium

multimedia:
  - gimp
  - darktable
  - vlc
  - mpv
  - gpodder

utilities:
  - keepassxc

developer_packages:
  - golang
  - make
  - python310
  - python39
  - python38
  - kubernetes-client
  - golang-sigs-k8s-kustomize
  - podman
  - podman-compose
  - skopeo
  - buildah
